base: /
errorHandling:
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=48'
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=16'
languages:
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 0
rootPageId: 1
websiteTitle: 'Open OAP'
